AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for ECS Fargate with Secrets Manager, MariaDB, HTTPD service, and ALB.

Resources:
  # ECS Cluster
  ECSCluster:
    Type: AWS::ECS::Cluster

  # Application Load Balancer
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - !ImportValue PublicSubnet1Id
        - !ImportValue PublicSubnet2Id
      SecurityGroups:
        - !ImportValue LoadBalancerSecurityGroupId

  # Target Group for ECS Service
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      VpcId: !ImportValue VPCId
      TargetType: ip

  # Listener for the Application Load Balancer
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  # ECS Task Definition
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: "my-ecs-task"
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue ECSExecutionRole
      TaskRoleArn: !ImportValue ECSTaskRole
      ContainerDefinitions:
        - Name: "httpd-container"
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/arces-web-repo:latest"
          PortMappings:
            - ContainerPort: 80
          Secrets:
            - Name: DATABASE_HOST
              ValueFrom: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:mariadb-secrets-dev-host'
            - Name: DATABASE_USER
              ValueFrom: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:mariadb-secrets-dev-username'
            - Name: DATABASE_PASSWORD
              ValueFrom: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:mariadb-secrets-dev-password'
            - Name: DATABASE_NAME
              ValueFrom: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:mariadb-secrets-dev-dbname'

  # ECS Service
  ECSService:
    Type: AWS::ECS::Service
    DependsOn: ECSTaskDefinition
    Properties:
      Cluster: !Ref ECSCluster
      LaunchType: FARGATE
      TaskDefinition: !Ref ECSTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue PrivateSubnet1Id
            - !ImportValue PrivateSubnet2Id
          SecurityGroups:
            - !ImportValue AppSecurityGroupId
      DesiredCount: 1
      LoadBalancers:
        - ContainerName: "httpd-container"
          ContainerPort: 80
          TargetGroupArn: !Ref TargetGroup

Outputs:
  ECSClusterName:
    Description: "Name of the ECS Cluster"
    Value: !Ref ECSCluster

  ECSTaskDefinitionArn:
    Description: "ARN of the ECS Task Definition"
    Value: !Ref ECSTaskDefinition

  ECSServiceName:
    Description: "Name of the ECS Service"
    Value: !Ref ECSService

  LoadBalancerDNS:
    Description: "DNS name of the Load Balancer"
    Value: !GetAtt ApplicationLoadBalancer.DNSName
