AWSTemplateFormatVersion: '2010-09-09'
Description: Plantilla CloudFormation para ECS Fargate con integración de Secrets Manager y conexión a MariaDB.

Resources:
  # ECS Cluster
  ECSCluster:
    Type: AWS::ECS::Cluster

  # ECS Task Definition
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: "my-ecs-task"
      Cpu: "256" # Configura según tus necesidades
      Memory: "512" # Configura según tus necesidades
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue ECSExecutionRoleArn
      TaskRoleArn: !ImportValue ECSTaskRoleArn
      ContainerDefinitions:
        - Name: "my-container"
          Image: "mi-imagen-de-contenedor" # Reemplaza con tu imagen de contenedor
          PortMappings:
            - ContainerPort: 80
          Secrets:
            - Name: DATABASE_HOST
              ValueFrom: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:mariadb-secrets-dev-host'
            - Name: DATABASE_USER
              ValueFrom: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:mariadb-secrets-dev-username'
            - Name: DATABASE_PASSWORD
              ValueFrom: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:mariadb-secrets-dev-password'
            - Name: DATABASE_NAME
              ValueFrom: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:mariadb-secrets-dev-dbname'

  # ECS Service
  ECSService:
    Type: AWS::ECS::Service
    DependsOn: ECSTaskDefinition
    Properties:
      Cluster: !Ref ECSCluster
      LaunchType: FARGATE
      TaskDefinition: !Ref ECSTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue PublicSubnet1Id
            - !ImportValue PublicSubnet2Id
          SecurityGroups:
            - !ImportValue SecurityGroupId
      DesiredCount: 1

  # Actualización del Rol de la Tarea de ECS para acceso a Secrets Manager
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: "/"
      Policies:
        - PolicyName: "ECSTaskPolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:mariadb-secrets-dev-*'

Outputs:
  ECSClusterName:
    Description: "Nombre del Cluster de ECS"
    Value: !Ref ECSCluster

  ECSTaskDefinitionArn:
    Description: "ARN de la definición de la tarea ECS"
    Value: !Ref ECSTaskDefinition

  ECSServiceName:
    Description: "Nombre del servicio ECS"
    Value: !Ref ECSService
