AWSTemplateFormatVersion: '2010-09-09'
Description: Plantilla CloudFormation para ECS Fargate con integración de Secrets Manager, conexión a MariaDB y servicio HTTPD.

Resources:
  # ECS Cluster
  ECSCluster:
    Type: AWS::ECS::Cluster

  # (Opcional) Repositorio ECR para la imagen HTTPD
  HTTPDRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "arces-web-repo"

  # ECS Task Definition
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: "my-ecs-task"
      Cpu: "256" # Configura según tus necesidades
      Memory: "512" # Configura según tus necesidades
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue ECSExecutionRoleArn
      TaskRoleArn: !ImportValue ECSTaskRoleArn
      ContainerDefinitions:
        - Name: "httpd-container"
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/arces-web-repo:latest"
          PortMappings:
            - ContainerPort: 80
          Secrets:
            - Name: DATABASE_HOST
              ValueFrom: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:mariadb-secrets-dev-host'
            - Name: DATABASE_USER
              ValueFrom: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:mariadb-secrets-dev-username'
            - Name: DATABASE_PASSWORD
              ValueFrom: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:mariadb-secrets-dev-password'
            - Name: DATABASE_NAME
              ValueFrom: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:mariadb-secrets-dev-dbname'

  # ECS Service
  ECSService:
    Type: AWS::ECS::Service
    DependsOn: ECSTaskDefinition
    Properties:
      Cluster: !Ref ECSCluster
      LaunchType: FARGATE
      TaskDefinition: !Ref ECSTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue PublicSubnet1Id
            - !ImportValue PublicSubnet2Id
          SecurityGroups:
            - !ImportValue SecurityGroupId
      DesiredCount: 1

Outputs:
  ECSClusterName:
    Description: "Nombre del Cluster de ECS"
    Value: !Ref ECSCluster

  ECSTaskDefinitionArn:
    Description: "ARN de la definición de la tarea ECS"
    Value: !Ref ECSTaskDefinition

  ECSServiceName:
    Description: "Nombre del servicio ECS"
    Value: !Ref ECSService

  ECRRepositoryURI:
    Description: "URI del repositorio ECR para HTTPD"
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/arces-web-repo"
