AWSTemplateFormatVersion: '2010-09-09'
Description: Plantilla CloudFormation para desplegar un servicio ECS Fargate para un sitio web.

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster

  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: "web-app"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue ECSExecutionRole
      TaskRoleArn: !ImportValue ECSTaskRole
      Cpu: "256"
      Memory: "512"
      ContainerDefinitions:
        - Name: "web-container"
          Image: "977685339165.dkr.ecr.us-east-2.amazonaws.com/python"
          PortMappings:
            - ContainerPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: "ecs-logs"
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: "ecs"

  ECSFargateService:
    Type: AWS::ECS::Service
    DependsOn: LoadBalancerListener
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref ECSTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue PublicSubnet1Id
            - !ImportValue PublicSubnet2Id
          SecurityGroups:
            - !ImportValue AppSecurityGroupId
      LoadBalancers:
        - ContainerName: "web-container"
          ContainerPort: 80
          TargetGroupArn: !Ref ECSFargateTargetGroup

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - !ImportValue PublicSubnet1Id
        - !ImportValue PublicSubnet2Id
      SecurityGroups:
        - !ImportValue LoadBalancerSecurityGroupId

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ECSFargateTargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

  ECSFargateTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      TargetType: ip  # Tipo de objetivo configurado como 'ip'.
      VpcId: !ImportValue VPCId

Outputs:
  ECSClusterName:
    Description: "Nombre del cluster ECS"
    Value: !Ref ECSCluster
  ECSFargateServiceArn:
    Description: "ARN del servicio ECS Fargate"
    Value: !Ref ECSFargateService
  LoadBalancerDNS:
    Description: "DNS del Load Balancer"
    Value: !GetAtt LoadBalancer.DNSName
