AWSTemplateFormatVersion: '2010-09-09'
Description: Plantilla CloudFormation para ECS Fargate con integración de Secrets Manager, conexión a MariaDB y servicio HTTPD.

Resources:
  # ECS Cluster
  ECSCluster:
    Type: AWS::ECS::Cluster

  # ECS Task Definition
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: "my-ecs-task"
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue ECSExecutionRoleArn
      TaskRoleArn: !ImportValue ECSTaskRoleArn
      ContainerDefinitions:
        - Name: "httpd-container"
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/arces-web-repo:latest"
          PortMappings:
            - ContainerPort: 80
          Secrets:
            - Name: DATABASE_HOST
              ValueFrom: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:mariadb-secrets-dev-host'
            - Name: DATABASE_USER
              ValueFrom: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:mariadb-secrets-dev-username'
            - Name: DATABASE_PASSWORD
              ValueFrom: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:mariadb-secrets-dev-password'
            - Name: DATABASE_NAME
              ValueFrom: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:mariadb-secrets-dev-dbname'

  # ECS Service
  ECSService:
    Type: AWS::ECS::Service
    DependsOn: ECSTaskDefinition
    Properties:
      Cluster: !Ref ECSCluster
      LaunchType: FARGATE
      TaskDefinition: !Ref ECSTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue PrivateSubnet1Id
            - !ImportValue PrivateSubnet2Id
          SecurityGroups:
            - !ImportValue AppSecurityGroupId
      DesiredCount: 1
      LoadBalancers:
        - ContainerName: "httpd-container"
          ContainerPort: 80
          TargetGroupArn: !Ref TargetGroup

  # Target Group for ECS Service
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      VpcId: !ImportValue VPCId
      TargetType: ip

  # Application Load Balancer Listener
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !ImportValue LoadBalancerArn
      Port: 80
      Protocol: HTTP

Outputs:
  ECSClusterName:
    Description: "Nombre del Cluster de ECS"
    Value: !Ref ECSCluster

  ECSTaskDefinitionArn:
    Description: "ARN de la definición de la tarea ECS"
    Value: !Ref ECSTaskDefinition

  ECSServiceName:
    Description: "Nombre del servicio ECS"
    Value: !Ref ECSService

  ECRRepositoryURI:
    Description: "URI del repositorio ECR para HTTPD"
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/arces-web-repo"
